model:
  name: hit
  params:
    image_size: 224
    blocks: [4, 4, 4]
    num_heads: 6
    block_dims: [384, 384, 384]
    mlp_ratio: 4
    dropout: 0.0
    attention_dropout: 0.2
    mlp_dropout: 0.0
    drop_path: 0.0
    num_classes: 1000
    patch_size: 8
    use_pos_tokens: True
    block_version: 'hit'
